### ISSUE TITLE
Streamlining bedboss running

### ISSUE THREAD

**Issue by nsheff** [databio/bedbase#49]
A collection of bedbase-related issues from when I tried to run things:

- [x] if missing the `path.vec2vec` config option, the `bedboss` pipeline starts, but then fails when it tries to create this. This should be smarter and check for everything it needs at the beginning.
- [x] besides this, the hg38_metadata_BED_testing.h5 shouldn't be necessary for bedboss since no text processing happens. Currently, the pipeline fails if it's not there; but it shouldn't even be using it. it's required by bbconf because it's used by bedhost; but that doesn't mean it should be required by bedboss...
[ALEX response: I don't see this dependency, to solve this issue I need to know where was the error, or problem]
- [x] bedboss pytests take way too long, and they fail on my computer (I think they require some setup. a message should state that. maybe it's because I don't have the test database loaded... just tell me that, then). the pytest should check if the database is available. if not, it should not run those tests. this could probably be accomplished with a `@requires_database` decorator.
- [x] should bedboss really be a CLI install? Or just a script? maybe just add dev documentation on how to run it as a script.
- [x] bbconf is still using AttMap? No, dev version no longer is using attmap!
- [x] bedset.backend.get_records() needs to handle paging (https://github.com/pepkit/pipestat/issues/75)
- [x] bbconf object has an attribute called 'qdrant_client', but that overloads the package name... it's actually a geniml.QdrantBackend, which is confusing.
