### ISSUE TITLE
2024-03 BEDbase sprint

### ISSUE THREAD

**Issue by nsheff** [databio/bedbase#62]
This issue is to track our vision for immediate BEDbase development in 2024 March/April.

### Current deployment:
- bedhost v0.3.0
- bedhost-ui v0.3.0
- bbconf v0.4.2
- bedboss v0.1.0

### Target Deployment for April 3 (for April 10 demo)
- [x] bedhost v0.4.0 - [databio/bedhost/milestone/3](https://github.com/databio/bedhost/milestone/3)
- [x] bedhost-ui v0.4.0
- [x] bedboss v0.2.0 - https://github.com/databio/bedboss/milestone/5
- [x] bbconf v0.5.0

### Main targets for this sprint:
- [x] documentation (#63)
- [x] add text-to-bed search (databio/bedhost#96)
- [x] implement bed-to-bed search: databio/bedhost#94
- [x] polish API, make sure examples and autodocs are good

### Misc API updates:
- [x] add the text-to-bed version to the /service-info endpoint and version badges shown on the UI.
- [x] address Sean's feedback.

**Comment by khoroshevskyi** [comment]
All of the points were fixed in this sprint
