### ISSUE TITLE
Roadmap for asynchronous BEDbase/BEDboss data processing

### ISSUE THREAD

**Issue by nsheff** [databio/bedbase#84]
We need these components for asynchronous processing of BED files to populate bedbase.

1. [x] Automatic registering of new BED files posted to GEO.
  - we are already automatically creating a PEP with new BED files using github action
  - `bbuploader` process reads from PEPhub (run by `bedboss geo upload-all`)
  - [x] implement `--light` CLI arg for `bedboss geo upload --light ...` (compute ID, upload BED file, collect and input metadata)
  - [x] add new github action that will run this process weekly.
  - [x] make sure current endpoints properly ignore "stub" records, if needed (those that haven't yet gone through full/heavy process).
2. [x] Allowing users to register new BEDsets
  - [x] endpoint for registering a BEDset 
  	- POST a PEPhub registry path. BEDbase retrieves this PEP, validates against BEDbase::bedset schema, and then creates a new BEDset in the database. (This relies completely on pephub auth, so no further auth is required?) This should 1. validate against PEP schema. Do other validations. Limit size for now to, say 2k BEDs? maybe limit throughput? Maybe to start, hard code a list of "allowed" pephub namespaces.
  	- [x] Create a button on BEDbase cart page to "Create BEDset PEP for this Cart". (This would require user to authenticate with PEPhub...)
3. [x] Daemon that retrieves unprocessed BED files and processes them (plots and statistics)
   - [x] endpoint for unprocessed files ?
   - [x] endpoint for unprocessed plots
   - [x] endpoint for unprocessed statistics
   - [x] script thats hits these endpoints, and then does the correct processing (in BEDboss)
   - [x] wrapper daemon to sleep and wrap the above script.
4. [x] Daemon that retrieves unprocessed BED sets and processes them.
   - [x] endpoint for retrieving which BEDsets are registered, but not processed
   - [x] script thats hits bedset endpoints, and then does the correct processing (in BEDboss)
   - [x] wrapper daemon to sleep and wrap the above script.

**Comment by khoroshevskyi** [comment]
To run unprocessed bed files that are in the database I implemented the function in bedboss:
```
bedboss reprocess-all ...
```

**Comment by khoroshevskyi** [comment]
Fixes needed before closing this issue:
- [ ] Release new geniml
- [ ] Fix https://github.com/databio/bedboss/issues/89
- [ ] Fix warning for Python 3.12
- [ ] Start cron job for the docker container
